#!/opt/homebrew/bin/bash

[[ ${#*} -lt 4 ]] && echo "Expecting four three letter arguments, e.g., abo gpq hei stv" && exit 1

[[ ! -z "${5}" ]] && first="${5}"
quote="'"
all_letters="${1}${2}${3}${4}"

grepexp="grep -E ${quote}^${first}("
filterexp=""
for i in {1..4}; do
    grepexp="${grepexp}(${1:0:1}|${1:1:1}|${1:2:1})?"
    filterexp="${filterexp} $(echo {${1:0:1},${1:1:1},${1:2:1}}{${1:0:1},${1:1:1},${1:2:1}})"
    shift
done
grepexp="${grepexp})+\$${quote} /usr/share/dict/web2"

filterexp=$(echo ${filterexp} | sed 's/ /\\|/g')

eval ${grepexp} | while read word; do
     [[ ${#word} -lt 3 ]] || [[ ${#word} -gt 12 ]] && continue
    echo ${#word} ${word}
done |\
    grep -v ${filterexp} |\
    sort -n | cut -d' ' -f2 |\
    while read word; do
	echo "${word} $(echo $word |sed 's/\(.\)/\1\n/g' | grep -v ^$ | sort | uniq | wc -l)"
    done


# | while read word; do echo $(echo $word | sed 's/\(.\)/\1\n/g' | grep -v "^$" | sort | uniq -c |
# wc -l) ${word}; done | sort -n


