#!/opt/homebrew/bin/bash

# Load dictionary into memory
declare -A DICT
while IFS= read -r w; do
    w="${w^^}"    # Internal dictionary set to all upper on load
    DICT["$w"]=1
done < "$DEFAULT_DICT"

in_dict() {
    local w="${1^^}"
    [[ ${DICT["$w"]+_} ]]
}

items=("$@")
len="${#items[@]}"
: > .quartiles.txt   # truncate

# Show arguments for typos
for (( i=0; i< len/4; i++ )); do
    big=""
    for (( j=0; j<4; j++ )); do
        index=$(( i*4 + j ))
        echo -n "${items[index]}"
        big+="${items[index]}"
        [[ $j -lt 3 ]] && echo -n "-"
    done
    if ! in_dict "$big"; then
        echo -n " (not found)"
    else
        echo "${big^^}" >> .quartiles.txt
    fi
    echo
done
echo "=================="

# Generate list of words
for (( i=0; i<len; i++ )); do
    echo "${items[i]}" >> .quartiles.txt
    for (( j=0; j<len; j++ )); do
        (( j == i )) && continue
        echo "${items[i]}${items[j]}" >> .quartiles.txt
        for (( k=0; k<len; k++ )); do
            (( k == i || k == j )) && continue
            echo "${items[i]}${items[j]}${items[k]}" >> .quartiles.txt
        done
    done
done

touch .q
while read -r word; do
    [[ ${#word} -lt 3 ]] && continue
    wordu="${word^^}"

    if in_dict "$word"; then
        echo "$word"
    fi
done < .quartiles.txt >> .q

sort -u .q | tr '[:upper:]' '[:lower:]' > .quartiles.txt
rm .q
echo "$(echo $(cat .quartiles.txt | wc -l)) words found."
cat .quartiles.txt
