#!/usr/bin/env bash

###############################################################################
# 
# sleep - a script that is called when this mac goes to sleep
#
# $Id: .sleep-v 1.20 2013-10-27 12:58:39-07 dan Exp $
#
###############################################################################

###############################################################################
# Functions 
###############################################################################

function maybeTalk() {
    [[ ! ${o_talk} ]] && return
    v=$(osascript -e 'output volume of (get volume settings)')
    m=$(osascript -e 'output muted of (get volume settings)')
    osascript -e 'set volume output volume 30'
    osascript -e 'set volume without output muted'
    say "$@"
    osascript -e "set volume output volume ${v}"
    [[ "${m}" == "true" ]] && w="with" || w="without"
    osascript -e "set volume ${w} output muted"
}

###############################################################################
# Code
###############################################################################

o_talk=true

logger -is "Sleeping"

[[ -r "${HOME}/.bashrc" ]] && source "${HOME}/.bashrc" || logger -is "No .bashrc"

clog "Sleeping"
maybeTalk "Sleeping"
clog ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
clog "pid $$ as user ${USER} ($UID) ($EUID) called by ${whorang} $*"
#diskutil eject "USB Time Machine" 2> /dev/null

# [[ $(ps axo pid,command | grep "[M]essages") ]] && osascript -e 'tell app "Messages" to log out'

[[ $(ps axo pid,command | grep "[S]kype") ]] && osascript -e 'tell app "Skype" to send command "SET USERSTATUS OFFLINE" script name "sleep"' 2> /dev/null

clog "normal exit"

exit 0
