#!/usr/bin/env bash
###############################################################################
#
# today - closes and reopens network connections, measuring bandwidth
#
###############################################################################

source ~/.bash_profile
echo "Starting by looking at SSID and running ipinfo..."
ssid="$(airport -I | grep " SSID:" | awk '{print $2}')"
clog "Initiating, SSID is ${ssid}"
ipinfo
if [[ "${ssid}" == "ELPP" ]]; then
    echo "Logging bandwidth..."
    clog $(bandwidth papamini.local)
fi
echo "Taking en0 down, sleeping then up again..."
sudo ifconfig "${aptdev:-en0}" down
sleep 3
sudo ifconfig "${aptdev:-en0}" up
sleep 1
ipinfo
echo "Running bandwidth again..."
clog $(bandwidth papamini.local)
bandwidth papamini.local

