#!/usr/bin/env bash
###############################################################################
#
# vpn - starts or stops the vpn along with McAfee virus
#       put in your path and make it executable by $ chmod +x vpn.
#       If not in your path, execute with ./vpn start or ./vpn stop
#
###############################################################################

if [[ ! "${1}" ]]; then
    # Nothing - start the cisco VPN
    # prompt for password if invalid, otherwise updates env
    eval $(op signin --session "${OP_SESSION_gerrity_benditt}")
    endpoint="$(op get item $OP_VPN_KEY | jq '.overview.URLs[] | select(.u | contains("twv")).u' | sed 's/\"//g')"
    un="$(op get item $OP_VPN_KEY --fields username)"
    pw="$(op get item $OP_VPN_KEY --fields password)"
    print "-s connect ${endpoint}\n  /opt/cisco/anyconnect/bin/vpn 
elif [[ "${1}" == "disconnect" ]]; then
    /opt/cisco/anyconnect/bin/vpn disconnect
elif [[ "${1}" == "start" ]]; then
   [[ $(ps aux | grep "[c]isco/anyconnect") ]] && osascript -e 'tell app "Cisco AnyConnect Secure Mobility Client" to quit'
   echo "Enabling McAfee..."
   sudo defaults write /Library/Preferences/com.mcafee.ssm.antimalware.plist OAS_Enable -bool True
   sudo /usr/local/McAfee/AntiMalware/VSControl stop
   sudo /usr/local/McAfee/AntiMalware/VSControl reload
   echo "Starting VPN..."
   open -a "Cisco AnyConnect Secure Mobility Client"
elif [[ "${1}" == "stop" ]]; then
   echo "Quitting Cisco..."
   [[ $(ps aux | grep "[c]isco/anyconnect") ]] && osascript -e 'tell app "Cisco AnyConnect Secure Mobility Client" to quit'
   echo "Stopping McAfee..."
   sudo defaults write /Library/Preferences/com.mcafee.ssm.antimalware.plist OAS_Enable -bool False
   sudo /usr/local/McAfee/AntiMalware/VSControl stop
   sudo /usr/local/McAfee/AntiMalware/VSControl reload
else
    echo "Usage: vpn [start|stop|disconnect]"
fi


